heat_template_version: 2013-05-23

description: >
  Heat template to support Cirros, written by Alta3 Research

parameters:

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
  instance_type:
    type: string
    description: Provides the size, or flavor, of the VM server
    default: m1.tiny
  image_id:
    type: string
    description: >
      Name or ID of the image to use for the server
    default: cirros
  network_name:
    type: string
    description: the network to use
  

resources:
  alta3_heat_stack:
    type: OS::Nova::Server
    properties:
      networks:
        - network: { get_param: network_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
